# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogRotasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 155)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 110, 221, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 241, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbSudut = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lbSudut.setFont(font)
        self.lbSudut.setObjectName("lbSudut")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbSudut)
        self.inputSudut = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.inputSudut.setObjectName("inputSudut")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inputSudut)
        self.lbPusatX = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lbPusatX.setFont(font)
        self.lbPusatX.setObjectName("lbPusatX")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbPusatX)
        self.inputPusatX = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.inputPusatX.setObjectName("inputPusatX")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputPusatX)
        self.lbPusatY = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.lbPusatY.setFont(font)
        self.lbPusatY.setObjectName("lbPusatY")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbPusatY)
        self.inputPusatY = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.inputPusatY.setObjectName("inputPusatY")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputPusatY)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbSudut.setText(_translate("Dialog", "Sudut"))
        self.lbPusatX.setText(_translate("Dialog", "Titik pusat X"))
        self.lbPusatY.setText(_translate("Dialog", "Titik pusat Y"))
        self.label_3.setText(_translate("Dialog", "Masukkan detail Rotasi"))
